matrix:
    include:
#        - os: linux
#          sudo: false
#          language: python
#          python: 3.6
#          env: TOXENV=py36
#        - os: linux
#          sudo: false
#          language: python
#          python: 3.5
#          env: TOXENV=py35
#        - os: linux
#          sudo: false
#          language: python
#          python: 2.7
#          env: TOXENV=py27
        - os: osx
          language: generic
          env: PYTHON=3.6.5

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew install python3
    brew upgrade python
    python --version
  fi

install:
  - python -m pip install -U pip
  - python setup.py install

script:
  - python BCO/_tests/runAll.py