language: python

matrix:
    include:
        - os: linux
          sudo: false
          python: 3.6
          env:
            global:
              - TOXENV=py36
              - PYTHON=3
        - os: linux
          sudo: false
          python: 2.7
          env:
            global:
              - TOXENV=py27
              - PYTHON=2
        - os: osx
          osx_image: xcode9.4
          language: generic
          env:
            global:
              - TOXENV=py36
              - PYTHON=3
        - os: osx
          osx_image: xcode9.4
          language: generic
          env:
            global:
              - TOXENV=py27
              - PYTHON=2



before_install:
    - |
       if [ "$TRAVIS_OS_NAME" = "osx" ]; then
         brew update
         brew install hdf5 netcdf

         if [ "$PYTHON" = "2" ]; then
           brew install python@2
           export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
         fi
       fi

install:
    - |
        if [ "$PYTHON" = "2" ]; then
            python --version
            python setup.py install
        else
            python3 --version
            python3 setup.py install
        fi


script:
    - |
        if [ "$PYTHON" = "2" ]; then
            python BCO/_tests/runAll.py

        else
            python3 BCO/_tests/runAll.py
        fi
