language: python


matrix:
    include:
        - os: linux
          sudo: false
          python: 3.6
          env: TOXENV=py36
#        - os: linux
#          sudo: false
#          python: 3.5
#          env: TOXENV=py35
#        - os: linux
#          sudo: false
#          python: 2.7
#          env: TOXENV=py27
#        - os: osx
#          python: 2.7
#          env: TOXENV=py27
#        - os: osx
#          python: 3.6
#          env: TOXENV=py36


script:
  - pyton BCO/_tests/hello.py
#  - python setup.py install
#  - python BCO/_tests/runAll.py