language: python


matrix:
    include:
        - os: linux
          sudo: false
          python: 3.6
          env: TOXENV=py36
        - os: linux
          sudo: false
          python: 35
          env: TOXENV=py35
        - os: linux
          sudo: false
          python: 2.7
          env: TOXENV=py27
        - os: osx
          python: 2.7
          env: TOXENV=py27
        - os: osx
          python: 3.6
          env: TOXENV=py36

script: BCO/_tests2/runAll.py