language: python
matrix:
  include:
  - os: linux
    sudo: false
    python: 2.7
    env:
      global:
      - TOXENV=py27
      - PYTHON=2
cache:
- pip
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update
    brew install hdf5 netcdf

    if [ "$PYTHON" = "2" ]; then
      brew install python@2
      export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"

    elif [ "$PYTHON" = "37" ]; then
      brew upgrade python

    elif [ "$PYTHON" = "35" ]; then
      pyenv install 3.5.2
      pyenv local 3.5.2
      PATH="~/.pyenv/versions/3.5.2/bin:${PATH}"
      pip3 install --upgrade pip
      pip3 install numpy
      pip3 install matplotlib
      pip3 install scipy
      pip3 install future
      pip3 install configparser
      pip3 install netcdf4
    fi
  fi
install:
- |
  if [ "$PYTHON" = "2" ]; then
      python --version
      pip install --upgrade pip
      pip install 'matplotlib==1.4'
      python setup.py install

  elif ["$PYTHON" = "35"]; then
      python3 --version
      python3 setup.py install

  else
      python3 --version
      python3 setup.py install
  fi
script:
- |
  if [ "$PYTHON" = "2" ]; then
      python BCO/_tests/runAll.py
      echo "asdf"

  elif ["$PYTHON" = "35"]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      touch ~/.matplotlib/matplotlibrc
      echo backend: TkAgg > ~/.matplotlib/matplotlibrc
    fi

      python3 BCO/_tests/runAll.py
  else
      python3 BCO/_tests/runAll.py
  fi
deploy:
  provider: pypi
  user: tmachnitzki
  password:
    secure: umjIj0tdS/Iv+sfMIDX9DMJdpjyc3on+4mja0va+/qP0NBk5S1qJJ+jyrtIXZjPn4g3YKpBc5zExJQye2bsqHnizswYCGynPr+UFSMZFd6ARY16HPUAoUDfFuq5JCDEwlVAuAz4zrb9i/icuyySgvwUEqxmP2aBC/0SXMMBgBX9xNc/oqtqOOB5v6X6oiiMQvlvkHWqN8Zh6vzt56KjokEUX7OBVwFYSRzxUYmozTH7YJC2TKrV7MN5kdhwCh8XMvoT7FHwWKcf+paIkzJ3889ghhGnakmrV4soNR4jhIFEzdA1fSn22ClK4gt+eluFq9xxFAebb2JtAHPEPqClo7DgNcWPfgmjaqfTAXQiTlOY3UjKZwvitawYtYJaOXbzrtAxdw0yAFGBMY9jxc5hYVcp0uPtbiGrIKkcuv2efizB43oCyNRjuGmiyA4OYBS6H/+OmS7hlLDDY5amSMCnB3cn1q3CBMkEBb3VnMkP67n1I/DSLG5tX97/IX2EdkvvY/dzpe5cC8TRZ/mdgaeb9VwBXjj+1WqlV4+zU/fay1VfzIunv0x21uuDR/7kLY9tTBWTzbhSIzii8QN1UgIT+rxgPlXcK8qY+FYVMz6gfp876wkKrZSGTgzLoktK6277lEBbjop917BAJwgKJ44ZOq8ML5HK1hrq4pvvWhUlGco8=
  on:
    branch: master
    python: 2.7
