language: python

matrix:
    include:
#        - os: linux
#          sudo: false
#          python: 3.6
#          env: TOXENV=py36
#        - os: linux
#          sudo: false
#          python: 3.5
#          env: TOXENV=py35
#        - os: linux
#          sudo: false
#          python: 2.7
#          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py36


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3.6; fi

install:
  - python --version
  - python setup.py install

script:
  - python BCO/_tests/runAll.py