language: python

matrix:
    include:
#        - os: linux
#          sudo: false
#          python: 3.6
#          env: TOXENV=py36
#        - os: linux
#          sudo: false
#          python: 3.5
#          env: TOXENV=py35
#        - os: linux
#          sudo: false
#          python: 2.7
#          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py36



before_install:
    - |
       if [ "$TRAVIS_OS_NAME" = "osx" ]; then
         brew update
         brew install hdf5 netcdf
         if [ "$PYTHON" = "2" ]; then
           brew install python@2
           export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
         else
           brew upgrade python  # upgrade to Python 3
         fi
       fi

install:
  - python3 --version
  - python3 setup.py install

script:
  - python3 BCO/_tests/runAll.py